services:
  trabalho03-linux:
    build: .
    container_name: trabalho03-linux
    ports:
      - "8080:80"
    volumes:
      - ecommerce_dados:/app/ecommerce
      - ./backups:/app/backups
      - ./logs:/app/logs
    tty: true
    stdin_open: true

volumes:
  ecommerce_dados: